"""Initial migration

Revision ID: 8a22d4261acb
Revises: 
Create Date: 2023-03-24 17:52:59.168636

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8a22d4261acb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_groups_id', table_name='user_groups')
    op.drop_index('ix_user_groups_name', table_name='user_groups')
    op.drop_table('user_groups')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
                    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.Column('isbn', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
                    sa.Column('fk_publisher_id', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['fk_publisher_id'], ['publisher.publisher_id'], name='fk_book_publisher'),
                    sa.PrimaryKeyConstraint('book_id', name='book_pkey')
                    )
    op.create_table('publisher',
                    sa.Column('publisher_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('org_name', sa.VARCHAR(), autoincrement=False, nullable=False),
                    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('publisher_id', name='publisher_pkey')
                    )
    op.create_table('users',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='users_pkey')
                    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('user_groups',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='user_groups_pkey')
                    )
    op.create_index('ix_user_groups_name', 'user_groups', ['name'], unique=False)
    op.create_index('ix_user_groups_id', 'user_groups', ['id'], unique=False)
    # ### end Alembic commands ###
