"""empty message

Revision ID: c2a8af506732
Revises: 8a22d4261acb
Create Date: 2023-03-24 18:49:33.785524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a8af506732'
down_revision = '8a22d4261acb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_groups_id', table_name='user_groups')
    op.drop_index('ix_user_groups_name', table_name='user_groups')
    op.execute('DROP TABLE user_groups CASCADE')
    op.drop_table('publisher')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.execute('DROP TABLE users CASCADE')
    op.drop_index('ix_user_group_memberships_id', table_name='user_group_memberships')
    op.drop_table('user_group_memberships')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group_memberships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], name='user_group_memberships_group_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_group_memberships_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_group_memberships_pkey')
    )
    op.create_index('ix_user_group_memberships_id', 'user_group_memberships', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], name='users_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('publisher',
    sa.Column('publisher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('org_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('publisher_id', name='publisher_pkey')
    )
    op.create_table('user_groups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_groups_pkey')
    )
    op.create_index('ix_user_groups_name', 'user_groups', ['name'], unique=False)
    op.create_index('ix_user_groups_id', 'user_groups', ['id'], unique=False)
    # ### end Alembic commands ###
